### ISSUE TITLE
'Data' Environment / Protocols are internal only?

### ISSUE THREAD

**Issue by rbuencamino** [AndrewBarba/alpaca-swift#2]
Environment.data is marked as internal, as is the initializer for AlpacaDataClient. I'm curious as to why this is the case - currently your library has no public means for accessing the Alpaca data API.

**Comment by AndrewBarba** [comment]
Hey @rbuencamino, you can access the data client off the main `AlpacaClient` https://github.com/AndrewBarba/alpaca-swift/blob/main/Sources/Alpaca/AlpacaClient.swift#L11

Hope that helps

**Comment by rbuencamino** [comment]
👍🏼 thanks! don't know why I didn't see that.
